<?php
return [
  [
    'category' => 'Антидетект-браузеры',
    'title' => 'Vision',
    'content' => 'Антидетект-браузер',
    'benefit' => 'Скидка 20% на первую покупку',
    'promo_code' => 'SECRETVISION',
    'promo_note' => null,
    'link_url' => null,
    'link_label' => 'Перейти',
    'company_url' => null,
    'featured' => false,
    'menu_order' => 10,
  ],
  [
    'category' => 'Антидетект-браузеры',
    'title' => 'Dolphin',
    'content' => 'Антидетект-браузер',
    'benefit' => 'Скидка 20% на первую оплату',
    'promo_code' => 'SecretRoom',
    'promo_note' => null,
    'link_url' => null,
    'link_label' => 'Перейти',
    'company_url' => null,
    'featured' => false,
    'menu_order' => 20,
  ],
  [
    'category' => 'Антидетект-браузеры',
    'title' => 'Binom',
    'content' => 'Антидетект-браузер',
    'benefit' => 'Месяц бесплатно и скидка 40% на оплату второго месяца',
    'promo_code' => 'SecretRoom',
    'promo_note' => null,
    'link_url' => null,
    'link_label' => 'Перейти',
    'company_url' => null,
    'featured' => true,
    'menu_order' => 30,
  ],
  [
    'category' => 'Антидетект-браузеры',
    'title' => 'Octo Browser',
    'content' => 'Антидетект-браузер',
    'benefit' => 'Скидка 30% на первую оплату',
    'promo_code' => 'SECRETROOM30',
    'promo_note' => 'При регистрации по ссылке введите промокод: SECRETROOM30',
    'link_url' => null,
    'link_label' => 'Перейти',
    'company_url' => null,
    'featured' => false,
    'menu_order' => 40,
  ],
  [
    'category' => 'Клоакинг',
    'title' => 'Cloaking House',
    'content' => 'Сервис клоакинга для арбитража',
    'benefit' => 'Скидка 30% на любую подписку',
    'promo_code' => 'IGAMCAL30',
    'promo_note' => null,
    'link_url' => null,
    'link_label' => 'Перейти',
    'company_url' => null,
    'featured' => false,
    'menu_order' => 10,
  ],
  [
    'category' => 'Карты',
    'title' => 'Combo Cards',
    'content' => 'Сервис по выпуску виртуальных карт',
    'benefit' => '40 карт бесплатно',
    'promo_code' => 'SECRETROOM',
    'promo_note' => 'Ссылка для регистрации и промокод SECRETROOM',
    'link_url' => null,
    'link_label' => 'Ссылка для регистрации',
    'company_url' => null,
    'featured' => true,
    'menu_order' => 10,
  ],
  [
    'category' => 'Приложения и PWA',
    'title' => 'TSL Apps',
    'content' => 'Аренда PWA-приложений под Gambling',
    'benefit' => '+10% к пополнению и 7 дней триала',
    'promo_code' => null,
    'promo_note' => null,
    'link_url' => null,
    'link_label' => 'Ссылка для регистрации',
    'company_url' => null,
    'featured' => false,
    'menu_order' => 10,
  ],
  [
    'category' => 'Приложения и PWA',
    'title' => 'Apps4You',
    'content' => 'Аренда PWA-приложений под Gambling',
    'benefit' => 'Скидка 10%',
    'promo_code' => 'SECRET10',
    'promo_note' => null,
    'link_url' => null,
    'link_label' => 'Перейти',
    'company_url' => null,
    'featured' => false,
    'menu_order' => 20,
  ],
  [
    'category' => 'Дизайнеры креативов',
    'title' => 'Mafia Creo',
    'content' => 'Студия создания рекламных креативов',
    'benefit' => 'Скидка 20% на первый заказ',
    'promo_code' => 'крео20',
    'promo_note' => null,
    'link_url' => null,
    'link_label' => 'Перейти',
    'company_url' => null,
    'featured' => false,
    'menu_order' => 10,
  ],
  [
    'category' => 'Spy-сервисы',
    'title' => 'Spy House',
    'content' => 'Профессиональный спай-сервис для поиска прибыльных рекламных креативов, связок и офферов в форматах Facebook и TikTok, Push, Inpage',
    'benefit' => 'Скидка 30%',
    'promo_code' => 'SECRETSPY',
    'promo_note' => null,
    'link_url' => null,
    'link_label' => 'Перейти',
    'company_url' => null,
    'featured' => true,
    'menu_order' => 10,
  ],
  [
    'category' => 'Трекеры',
    'title' => 'AIO (Tracker)',
    'content' => 'Трекер MTK для аналитики трафика',
    'benefit' => 'Два месяца по цене одного',
    'promo_code' => null,
    'promo_note' => null,
    'link_url' => null,
    'link_label' => 'Ссылка для регистрации',
    'company_url' => null,
    'featured' => false,
    'menu_order' => 10,
  ],
  [
    'category' => 'Софт для команд',
    'title' => 'AIO (ERP)',
    'content' => 'ERP-система для управления арбитражной командой',
    'benefit' => 'Скидка 20% на первый месяц',
    'promo_code' => null,
    'promo_note' => null,
    'link_url' => null,
    'link_label' => 'Ссылка для регистрации',
    'company_url' => null,
    'featured' => true,
    'menu_order' => 10,
  ],
  [
    'category' => 'Софт для команд',
    'title' => 'CostView',
    'content' => 'Учет расходов и финансов для медиабаинга',
    'benefit' => 'Скидка 20%',
    'promo_code' => null,
    'promo_note' => null,
    'link_url' => null,
    'link_label' => 'Ссылка для регистрации',
    'company_url' => null,
    'featured' => false,
    'menu_order' => 20,
  ],
  [
    'category' => 'Софт для команд',
    'title' => 'Affilka',
    'content' => 'AI-менеджер для серфинга по рабочим чатам: автоматизация переписок, сбор аналитики и ключевых данных по партнерам',
    'benefit' => 'Скидка 15%',
    'promo_code' => 'SECRETAFFILKA',
    'promo_note' => null,
    'link_url' => null,
    'link_label' => 'Перейти',
    'company_url' => null,
    'featured' => false,
    'menu_order' => 30,
  ],
  [
    'category' => 'Контент для сайтов (SEO)',
    'title' => 'iGamingTextLab',
    'content' => 'Контент для игроков на 45+ языках, который создают без ИИ реальные игроки',
    'benefit' => 'Скидка 15%',
    'promo_code' => 'SEOWAKE',
    'promo_note' => null,
    'link_url' => null,
    'link_label' => 'Перейти',
    'company_url' => null,
    'featured' => false,
    'menu_order' => 10,
  ],
  [
    'category' => 'Прокси',
    'title' => 'MangoProxy',
    'content' => 'Сервис с топовыми проксями',
    'benefit' => 'Скидка на резидентские прокси и статические ISP',
    'promo_code' => 'SECRETROOM',
    'promo_note' => 'Промокоды:

SECRETROOM 20% на резидентские прокси

SECRETPROXY 5% статические ISP',
    'link_url' => null,
    'link_label' => 'Перейти',
    'company_url' => null,
    'featured' => false,
    'menu_order' => 10,
  ],
  [
    'category' => 'Прокси',
    'title' => 'ProxyShard',
    'content' => 'Прокси-сервис для PPC, SEO, парсинга и автоматизации',
    'benefit' => 'Скидка на прокси 15%',
    'promo_code' => 'secret',
    'promo_note' => 'Промокод при регистрации по ссылке:

secret  15% скидка на Datacentre (при заказа от месяца) и Residential прокси (стандартные)',
    'link_url' => null,
    'link_label' => 'Перейти',
    'company_url' => 'https://proxyshard.com',
    'featured' => false,
    'menu_order' => 20,
  ],
];
